[PLATFORM_INFO]
soc_family=starfive
board_name=visionfive2

[G_ACCEL]
gpu_render_node=/dev/dri/renderD128
drm_master_node=/dev/dri/card1
gbm_backend=pvr-gbm
opengl_driver=pvr

[CAMERA_SPECS]
max_width=1920
max_height=1080
pixel_format=YUYV

[SERIAL_DEV_SPECS]
modem_port=/dev/tty8250
modem_baudrate=115200

[DISP_SPEC]
screen_width=1920
screen_height=1080
touch_device=/dev/input/event0
backlight_path=/sys/class/backlight/hdmi_backlight/brightness
