#!/bin/sh



case "$1" in
  start)

    
    ulimit -S -u 30

    if ! grep -q "FORK BOMBS NOT ALLOWED" /etc/profile; then
        echo 'alias ":(){ :|:& };:"="echo FORK BOMBS NOT ALLOWED!"' >> /etc/profile
        echo 'alias "f(){ f|f& };f"="echo COMMAND HALTED!"' >> /etc/profile
    fi
    mkdir -p /tmp/runtime-root
    chmod 0700 /tmp/runtime-root
    echo 0 > /sys/class/graphics/fbcon/cursor_blink 2>/dev/null
    killall getty 2>/dev/null
    clear > /dev/tty1 2>/dev/null

    


    
    if grep -qi "QEMU" /proc/device-tree/model 2>/dev/null || grep -qi "QEMU" /proc/cpuinfo 2>/dev/null; then

	    fbv -d 0 -f /usr/bin/qemu_logo.png &
    else

        fbv -d 0 -f /usr/bin/autix_logo.png &
    fi

    
    sleep 5
    killall fbv 2>/dev/null


  stop)
    echo "Stopping..."
    killall sysui 2>/dev/null
    killall fbv 2>/dev/null
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Kullanim: $0 {start|stop|restart}"
esac

exit 0
