#!/bin/sh



case "$1" in
  start)
    echo "[AUTUMNOS] Setting DNS nameserver."
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    ulimit -S -u 30

    mkdir -p /tmp/runtime-root
    chmod 0700 /tmp/runtime-root
    echo 0 > /sys/class/graphics/fbcon/cursor_blink 2>/dev/null

    
    
    echo "[AUTUMNOS] Starting hardware watchdog"
    /usr/bin/AutixHardwareWatchdog &

    echo "[AUTUMNOS] Starting DRM/FBDEV surface detecting."
    /usr/bin/AutixSurfDetector &
    
    echo "[AUTUMNOS] Starting AutumnCore."
    /usr/bin/AutumnCore &

	if grep -q "QEMU" /proc/device-tree/model 2>/dev/null || grep -q "QEMU" /proc/cpuinfo; then
        fbv -f -u /usr/share/qemu.png > /dev/null 2>&1 &
    else
        fbv -f -u /usr/share/default.png > /dev/null 2>&1 &
    fi

    sleep 5
    killall fbv 2>/dev/null 
    echo "[AUTUMNOS] Starting GUI."
    /usr/bin/sysui &

    echo "[AUTUMNOS] Starting watchdog."
    (
            while true; do
                /usr/bin/watchdog.sh
                sleep 1
            done
        ) &
	;;

  stop)
    echo "[AUTUMNOS] Stopping system."
    killall sysui 2>/dev/null
    killall fbv 2>/dev/null
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Using: $0 {start|stop|restart}"
esac

exit 0
